#!/usr/bin/env python3
"""Create (or refresh) a course folder from the page template.

Usage:
  init_course.py COURSE_DIR --extract EXTRACT_DIR [--title T] [--ui-lang pl|en]
  init_course.py COURSE_DIR --update          # re-copy player files only (index.html, assets/, serve.py, start.*)

New course folder layout:
  index.html, assets/, serve.py, start.sh, start.bat, README.md   ← the player (from assets/template)
  content/course.json, content/<chapter-id>/…                     ← lessons you write (JSON)
  exercises/<dir>/…                                               ← programming exercises with tests
  course/data.js                                                  ← generated by build_course.py
  progress/                                                       ← learner progress (written by serve.py)
  .build/state.json, .build/source/                               ← build state + extracted book text
"""
import argparse
import datetime
import json
import os
import re
import shutil
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(os.path.dirname(HERE), "assets", "template")
PLAYER_FILES = ["index.html", "assets/app.js", "assets/style.css", "serve.py", "start.sh", "start.bat"]


def now():
    return datetime.datetime.now().astimezone().isoformat(timespec="seconds")


def slug(s):
    s = s.replace("ł", "l").replace("Ł", "L")
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:40] or "course"


def copy_player(dest, ui_lang):
    for rel in PLAYER_FILES:
        src, dst = os.path.join(TEMPLATE, rel), os.path.join(dest, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        if rel.endswith((".sh", ".py")):
            os.chmod(dst, 0o755)
    readme = os.path.join(TEMPLATE, "README.%s.md" % ("en" if ui_lang == "en" else "pl"))
    shutil.copyfile(readme, os.path.join(dest, "README.md"))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("course_dir")
    ap.add_argument("--extract", help="folder produced by extract_book.py")
    ap.add_argument("--title")
    ap.add_argument("--ui-lang", choices=["pl", "en"], help="language of the course (explanations + interface)")
    ap.add_argument("--update", action="store_true")
    a = ap.parse_args()
    dest = os.path.abspath(a.course_dir)

    if a.update:
        if not os.path.isdir(dest):
            sys.exit("No such course folder: %s" % dest)
        lang = "pl"
        try:
            lang = json.load(open(os.path.join(dest, "content", "course.json"), encoding="utf-8")).get("ui_lang", "pl")
        except (OSError, ValueError):
            pass
        copy_player(dest, lang)
        print("Player files refreshed in", dest, "(content, exercises and progress untouched). Run build_course.py to regenerate course/data.js.")
        return

    if not a.extract:
        sys.exit("--extract is required for a new course")
    manifest = json.load(open(os.path.join(a.extract, "manifest.json"), encoding="utf-8"))
    if os.path.exists(os.path.join(dest, ".build", "state.json")):
        sys.exit("%s already is a course (has .build/state.json). Use --update to refresh the player, or pick another folder." % dest)
    ui_lang = a.ui_lang or manifest.get("language") or "pl"
    title = a.title or manifest["title"]

    copy_player(dest, ui_lang)
    for d in ("content", "exercises", "course", "progress", ".build"):
        os.makedirs(os.path.join(dest, d), exist_ok=True)
    src_dst = os.path.join(dest, ".build", "source")
    if os.path.exists(src_dst):
        shutil.rmtree(src_dst)
    shutil.copytree(a.extract, src_dst)
    open(os.path.join(dest, "progress", ".gitkeep"), "w").close()

    course = {"id": slug(title), "title": title, "subtitle": "", "description": "", "ui_lang": ui_lang,
              "language": ui_lang, "level": "beginner",
              "source": {"title": manifest["title"], "author": manifest.get("author", ""), "file": manifest.get("source", "")}}
    with open(os.path.join(dest, "content", "course.json"), "w", encoding="utf-8") as f:
        json.dump(course, f, ensure_ascii=False, indent=2)

    chapters = []
    for c in manifest["chapters"]:
        chapters.append({"id": c["id"], "title": c["title"], "words": c["words"], "file": c["file"],
                         "status": "pending" if c["kind"] == "chapter" else "skipped", "lessons_built": 0, "note": ""})
    state = {"version": 1, "created": now(), "updated": now(),
             "book": {k: manifest.get(k, "") for k in ("title", "author", "language", "source", "format")},
             "ui_lang": ui_lang, "chapters": chapters, "notes": [], "log": [{"at": now(), "msg": "course initialised"}]}
    with open(os.path.join(dest, ".build", "state.json"), "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)
    print("Course scaffold ready in", dest)
    print("Next: write .build/plan.md (coverage plan), then content/<chapter-id>/… per chapter; use course_state.py to track progress.")


if __name__ == "__main__":
    main()
